<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-79L1OC3" failures="4" tests="8" name="Surefire test" time="0.1" errors="0" timestamp="2024-01-17T09:26:42 WAT">
  <testcase classname="dev.djob.id.AppTest" name="shouldAnswerWithTrue on shouldAnswerWithTrue(dev.djob.id.AppTest)" time="0.006"/>
  <testcase classname="dev.djob.id.EquationTest" name="testSolve_a_normal_negatif__b_null_c_normal_negatif_ on testSolve_a_normal_negatif__b_null_c_normal_negatif_(dev.djob.id.EquationTest)" time="0.014"/>
  <testcase classname="dev.djob.id.EquationTest" name="testSolve_a_proche_de_0_negatif__b_normal_positif__c_normal_positif_ on testSolve_a_proche_de_0_negatif__b_normal_positif__c_normal_positif_(dev.djob.id.EquationTest)" time="0.016"/>
  <testcase classname="dev.djob.id.EquationTest" name="testSolve_a_null_b_proche_de_0_positif__c_null on testSolve_a_null_b_proche_de_0_positif__c_null(dev.djob.id.EquationTest)" time="0.019">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;0.0&amp;gt; but was:&amp;lt;NaN&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<0.0> but was:<NaN>
at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.failNotEquals(Assert.java:743)
at org.junit.Assert.assertEquals(Assert.java:494)
at org.junit.Assert.assertEquals(Assert.java:592)
at dev.djob.id.EquationTest.testSolve_a_null_b_proche_de_0_positif__c_null(EquationTest.java:40)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- testSolve_a_null_b_proche_de_0_positif__c_null on testSolve_a_null_b_proche_de_0_positif__c_null(dev.djob.id.EquationTest) -->
  <testcase classname="dev.djob.id.EquationTest" name="testSolve_a_normal_positif__b_negatif_grand__c_grand_positif_ on testSolve_a_normal_positif__b_negatif_grand__c_grand_positif_(dev.djob.id.EquationTest)" time="0.027">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;0.0&amp;gt; but was:&amp;lt;0.06360769271850586&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<0.0> but was:<0.06360769271850586>
at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.failNotEquals(Assert.java:743)
at org.junit.Assert.assertEquals(Assert.java:494)
at org.junit.Assert.assertEquals(Assert.java:592)
at dev.djob.id.EquationTest.testSolve_a_normal_positif__b_negatif_grand__c_grand_positif_(EquationTest.java:525)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- testSolve_a_normal_positif__b_negatif_grand__c_grand_positif_ on testSolve_a_normal_positif__b_negatif_grand__c_grand_positif_(dev.djob.id.EquationTest) -->
  <testcase classname="dev.djob.id.EquationTest" name="testSolve_a_tres_proche_de_zero__b_normal_negatif__c_tres_proche_de_zero_ on testSolve_a_tres_proche_de_zero__b_normal_negatif__c_tres_proche_de_zero_(dev.djob.id.EquationTest)" time="0.027">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;0.0&amp;gt; but was:&amp;lt;8.060751829317883E-8&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<0.0> but was:<8.060751829317883E-8>
at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.failNotEquals(Assert.java:743)
at org.junit.Assert.assertEquals(Assert.java:494)
at org.junit.Assert.assertEquals(Assert.java:592)
at dev.djob.id.EquationTest.testSolve_a_tres_proche_de_zero__b_normal_negatif__c_tres_proche_de_zero_(EquationTest.java:137)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- testSolve_a_tres_proche_de_zero__b_normal_negatif__c_tres_proche_de_zero_ on testSolve_a_tres_proche_de_zero__b_normal_negatif__c_tres_proche_de_zero_(dev.djob.id.EquationTest) -->
  <testcase classname="dev.djob.id.EquationTest" name="testSolve_a_proche_de_0_positif__b_tres_proche_de_zero__c_tres_proche_de_0_negatif_ on testSolve_a_proche_de_0_positif__b_tres_proche_de_zero__c_tres_proche_de_0_negatif_(dev.djob.id.EquationTest)" time="0.03"/>
  <testcase classname="dev.djob.id.EquationTest" name="testSolve_a_tres_proche_de_0_negatif__b_proche_de_0_negatif__c_proche_de_0_positif_ on testSolve_a_tres_proche_de_0_negatif__b_proche_de_0_negatif__c_proche_de_0_positif_(dev.djob.id.EquationTest)" time="0.03">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;0.0&amp;gt; but was:&amp;lt;-4.0661785050133403E-10&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<0.0> but was:<-4.0661785050133403E-10>
at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.failNotEquals(Assert.java:743)
at org.junit.Assert.assertEquals(Assert.java:494)
at org.junit.Assert.assertEquals(Assert.java:592)
at dev.djob.id.EquationTest.testSolve_a_tres_proche_de_0_negatif__b_proche_de_0_negatif__c_proche_de_0_positif_(EquationTest.java:234)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- testSolve_a_tres_proche_de_0_negatif__b_proche_de_0_negatif__c_proche_de_0_positif_ on testSolve_a_tres_proche_de_0_negatif__b_proche_de_0_negatif__c_proche_de_0_positif_(dev.djob.id.EquationTest) -->
</testsuite> <!-- Surefire test -->
